global:
  url:
  prefix: "e!"
  replace: "nerd"
database:
  host:
  user:
  password:
  database:
twitter:
  accountname:
  consumer:
    key:
    secret:
  accesstoken:
    key:
    secret:
discord:
  token:
  ownerid: